### ISSUE TITLE
IN PROCESS - "Back" button on the Create Account page

### ISSUE THREAD

**Issue by gaswirth** [roundhousedesigns/rise-frontend#53]
There should be some way to navigate back to the login page and/or to "forgot password" from the create new account page. Providing a link would be helpful in the case where you try to create a new account but the email is already registered. You either need to go to login or need to reset your password.

**Comment by gacetta** [comment]
IN PROCESS - 
- reuse Chakra button to match "Create Account" button but with blue color
- button text "Back to login"
- include h3 text "Already have an account?"
- placement is top right of the page

**Comment by gacetta** [comment]
Wired up the button to navigate back to the login page.
Not the requested layout- wasn't able to figure out how to position in upper right without the use of absolute positioning or transform property due to the dynamically rendered "title" in the <Page> component.

Before:
<img width="1328" alt="Screen Shot 2023-06-18 at 12 21 32 PM" src="https://github.com/roundhousedesigns/rise-frontend/assets/78240758/847ca28f-9288-4ab0-8819-159a945b9b2b">
Current state:
<img width="1332" alt="Screen Shot 2023-06-18 at 12 20 34 PM" src="https://github.com/roundhousedesigns/rise-frontend/assets/78240758/cdcb9d4f-da2a-4f1b-8b7f-f5c0a1184c35">

**Comment by gaswirth** [comment]
Placement has been adjusted! I'll merge this soon 🤪 

Thanks, @gacetta!
